# Site
repository: abdelhaqs/abdelhaqs
favicon: images/favicon.ico

# Personal info
name: Abdelhak Ohammou
title: Data analyst
email: abdelhak.ohammou@uit.ac.ma
website: www.github.com/abdelhaqs/abdelhaqs

# Social links
twitter_username: #
github_username:  #
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: #
linkedin_username: #
# pinterest_username: jekyll
youtube_username: #
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>SQL</mark>, <mark>Python</mark> and <mark>Data Visualization</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and data analysis some of my other interests and hobbies are:
   - Rock climbing
   - Reading(#)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
